### PR TITLE
Feature/fix sonar remarks

### LINKED ISSUE #105: Fix SonarCloud bugs
SonarCloud found a [bug](https://sonarcloud.io/project/issues?id=yall&resolved=false&types=BUG).

### PR DESCRIPTION
**Pull request by qdeslandes**
Fix some of the SonarCloud remarks.

Fix #105

### CODE REVIEW

File: src/header.c [hunk 1]
```diff
@@ -122,14 +122,11 @@ static void set_matches_and_header(enum header_type hdr_type,
...
 	switch (hdr_type) {
-	case std_header:
-		*matches = std_matches;
-		*header = std_header_format;
-		break;
 	case call_header:
 		*matches = call_matches;
 		*header = call_header_format;
 		break;
+	case std_header:
```
Comment (qdeslandes) [inline src/header.c:129]: MINOR Remove this redundant "case" clause. [rule](https://sonarcloud.io/coding_rules#rule_key=c%3AS3458)

**Comment by Naccyde** [comment]
SonarQube analysis reported 2 issues
* ![BLOCKER][BLOCKER] 1 blocker
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

#### 1 extra issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![BLOCKER][BLOCKER] [yall.c#L220](https://github.com/Naccyde/yall/blob/599f47276df72b695f9c80ae299a8e711423169c/src/yall.c#L220): Review the data-flow; this memory allocation might not have been released when going out of scope. [rule](https://sonarcloud.io/coding_rules#rule_key=c%3AS3584)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by qdeslandes** [comment]
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
